# Generated by Django 5.2.8 on 2025-12-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('skins', '0003_alter_skin_desgaste'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Devolución')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolución')),
                ('estado', models.CharField(choices=[('Y', 'REALIZADO'), ('N', 'NO REALIZADO'), ('S', 'PENDIENTE')], verbose_name='Estado de Devolución')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.reserva')),
                ('id_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.skin')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
