# Generated by Django 5.2.8 on 2025-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre Usuario')),
                ('email', models.CharField(max_length=70, verbose_name='Email')),
                ('tel', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Balance')),
            ],
        ),
    ]
