# Generated by Django 5.2.8 on 2025-12-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skins', '0003_alter_skin_desgaste'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Movimiento')),
                ('tipo', models.CharField(choices=[('RES', 'RESERVA'), ('DEV', 'DEVOLUCIÓN')], verbose_name='Tipo Movimiento')),
                ('id_referencia', models.IntegerField(verbose_name='ID Referencia')),
                ('fecha_movimiento', models.DateField(verbose_name='Fecha del Movimiento')),
                ('id_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.skin')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
