# Generated by Django 5.2.8 on 2025-12-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skins', '0003_alter_skin_desgaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Imagen')),
                ('url', models.ImageField(null=True, upload_to='', verbose_name='Imagen Skin')),
                ('id_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.skin')),
            ],
        ),
    ]
