# Generated by Django 5.2.8 on 2025-11-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id_skin', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('desgaste', models.DecimalField(decimal_places=30, max_digits=30, verbose_name='float')),
                ('stattrack', models.BooleanField(verbose_name='stattrack')),
                ('precio', models.DecimalField(decimal_places=3, max_digits=3, verbose_name='precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
            ],
        ),
    ]
