# Generated by Django 5.2.8 on 2025-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='desgaste',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='float'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio'),
        ),
    ]
