# Generated by Django 5.2.8 on 2025-12-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0002_alter_skin_desgaste_alter_skin_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='desgaste',
            field=models.DecimalField(decimal_places=12, max_digits=13, verbose_name='float'),
        ),
    ]
