# Generated by Django 5.2.8 on 2025-12-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skins', '0003_alter_skin_desgaste'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Reserva')),
                ('estados', models.CharField(choices=[('FN', 'Recién Fabricado'), ('MW', 'Casi Nuevo'), ('FT', 'Algo Desgastado'), ('WW', 'Bastante Desgastado'), ('BS', 'Deplorable')], verbose_name='Estado Skin')),
                ('deposito', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Depósito')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha inicial')),
                ('fecha_final', models.DateField(verbose_name='Fecha final')),
                ('id_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.skin')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
